version: '3.8'

services:
  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api:3001
    env_file:
      - .env.local
    depends_on:
      - api
      - data
      - analytics
    networks:
      - defivitals-network

  # API Service (DeFi data)
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./services/api:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - defivitals-network

  # Data Service (Firebase operations)
  data:
    build:
      context: ./services/data
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    volumes:
      - ./services/data:/app
      - /app/node_modules
    env_file:
      - .env.local
    depends_on:
      - redis
    networks:
      - defivitals-network

  # Analytics Service
  analytics:
    build:
      context: ./services/analytics
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    volumes:
      - ./services/analytics:/app
      - /app/node_modules
    networks:
      - defivitals-network

  # Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - defivitals-network

volumes:
  redis-data:

networks:
  defivitals-network:
    driver: bridge 