version: '3.8'

services:
  # Frontend Service (Next.js)
  frontend:
    image: defivitals/frontend:latest
    working_dir: /app
    command: sh -c "mkdir -p node_modules && chown -R node:node . && su node -c 'npm install && npm run dev'"
    ports:
      - "3010:3000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api:3001
      - NEXT_PUBLIC_DATA_SERVICE_URL=http://data:3002
      - NEXT_PUBLIC_ANALYTICS_URL=http://analytics:3003
    env_file:
      - .env.local
    depends_on:
      - api
      - data
      - analytics
    networks:
      - defivitals-network

  # API Service (DeFi data)
  api:
    image: defivitals/api:latest
    ports:
      - "3007:3001"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - defivitals-network

  # Data Service (Firebase operations)
  data:
    image: defivitals/data:latest
    ports:
      - "3008:3002"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env.local
    depends_on:
      - redis
    networks:
      - defivitals-network

  # Analytics Service
  analytics:
    image: defivitals/analytics:latest
    ports:
      - "3009:3003"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - defivitals-network

  # Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - defivitals-network

volumes:
  redis-data:

networks:
  defivitals-network:
    driver: bridge 